use crate::cpu::instructions::{Condition, Instruction, Register8, Register16};

#[allow(dead_code)]
pub const OPCODE_TABLE: [Instruction; 256] = [
    // 0x00
    Instruction::NOP,
    Instruction::LD_r16_n16(Register16::BC, 0),
    Instruction::LD_BC_A(Register16::BC),
    Instruction::INC_r16(Register16::BC),
    Instruction::INC_r8(Register8::B),
    Instruction::DEC_r8(Register8::B),
    Instruction::LD_r8_n8(Register8::B, 0),
    Instruction::RLCA,
    Instruction::LD_n16_SP(0),
    Instruction::ADD_HL_r16(Register16::BC),
    Instruction::LD_A_BC(Register16::BC),
    Instruction::DEC_r16(Register16::BC),
    Instruction::INC_r8(Register8::C),
    Instruction::DEC_r8(Register8::C),
    Instruction::LD_r8_n8(Register8::C, 0),
    Instruction::RRCA,
    // 0x10
    Instruction::STOP,
    Instruction::LD_r16_n16(Register16::DE, 0),
    Instruction::LD_DE_A(Register16::DE),
    Instruction::INC_r16(Register16::DE),
    Instruction::INC_r8(Register8::D),
    Instruction::DEC_r8(Register8::D),
    Instruction::LD_r8_n8(Register8::D, 0),
    Instruction::RLA,
    Instruction::JR_e8(0),
    Instruction::ADD_HL_r16(Register16::DE),
    Instruction::LD_A_DE(Register16::DE),
    Instruction::DEC_r16(Register16::DE),
    Instruction::INC_r8(Register8::E),
    Instruction::DEC_r8(Register8::E),
    Instruction::LD_r8_n8(Register8::E, 0),
    Instruction::RRA,
    // 0x20
    Instruction::JR_cc_e8(Condition::NZ, 0),
    Instruction::LD_r16_n16(Register16::HL, 0),
    Instruction::LD_HLI_A,
    Instruction::INC_r16(Register16::HL),
    Instruction::INC_r8(Register8::H),
    Instruction::DEC_r8(Register8::H),
    Instruction::LD_r8_n8(Register8::H, 0),
    Instruction::DAA,
    Instruction::JR_cc_e8(Condition::Z, 0),
    Instruction::ADD_HL_r16(Register16::HL),
    Instruction::LD_A_HLI,
    Instruction::DEC_r16(Register16::HL),
    Instruction::INC_r8(Register8::L),
    Instruction::DEC_r8(Register8::L),
    Instruction::LD_r8_n8(Register8::L, 0),
    Instruction::CPL,
    // 0x30
    Instruction::JR_cc_e8(Condition::NC, 0),
    Instruction::LD_r16_n16(Register16::SP, 0),
    Instruction::LD_HLD_A,
    Instruction::INC_r16(Register16::SP),
    Instruction::INC_HL,
    Instruction::DEC_HL,
    Instruction::LD_HLINDIRECT_n8(0),
    Instruction::SCF,
    Instruction::JR_cc_e8(Condition::C, 0),
    Instruction::ADD_HL_r16(Register16::SP),
    Instruction::LD_A_HLD,
    Instruction::DEC_r16(Register16::SP),
    Instruction::INC_r8(Register8::A),
    Instruction::DEC_r8(Register8::A),
    Instruction::LD_r8_n8(Register8::A, 0),
    Instruction::CCF,
    /* 0x40 */
    Instruction::LD_r8_r8(Register8::B, Register8::B),
    Instruction::LD_r8_r8(Register8::B, Register8::C),
    Instruction::LD_r8_r8(Register8::B, Register8::D),
    Instruction::LD_r8_r8(Register8::B, Register8::E),
    Instruction::LD_r8_r8(Register8::B, Register8::H),
    Instruction::LD_r8_r8(Register8::B, Register8::L),
    Instruction::LD_r8_HLINDIRECT(Register8::B),
    Instruction::LD_r8_r8(Register8::B, Register8::A),
    Instruction::LD_r8_r8(Register8::C, Register8::B),
    Instruction::LD_r8_r8(Register8::C, Register8::C),
    Instruction::LD_r8_r8(Register8::C, Register8::D),
    Instruction::LD_r8_r8(Register8::C, Register8::E),
    Instruction::LD_r8_r8(Register8::C, Register8::H),
    Instruction::LD_r8_r8(Register8::C, Register8::L),
    Instruction::LD_r8_HLINDIRECT(Register8::C),
    Instruction::LD_r8_r8(Register8::C, Register8::A),
    /* 0x50 */
    Instruction::LD_r8_r8(Register8::D, Register8::B),
    Instruction::LD_r8_r8(Register8::D, Register8::C),
    Instruction::LD_r8_r8(Register8::D, Register8::D),
    Instruction::LD_r8_r8(Register8::D, Register8::E),
    Instruction::LD_r8_r8(Register8::D, Register8::H),
    Instruction::LD_r8_r8(Register8::D, Register8::L),
    Instruction::LD_r8_HLINDIRECT(Register8::D),
    Instruction::LD_r8_r8(Register8::D, Register8::A),
    Instruction::LD_r8_r8(Register8::E, Register8::B),
    Instruction::LD_r8_r8(Register8::E, Register8::C),
    Instruction::LD_r8_r8(Register8::E, Register8::D),
    Instruction::LD_r8_r8(Register8::E, Register8::E),
    Instruction::LD_r8_r8(Register8::E, Register8::H),
    Instruction::LD_r8_r8(Register8::E, Register8::L),
    Instruction::LD_r8_HLINDIRECT(Register8::E),
    Instruction::LD_r8_r8(Register8::E, Register8::A),
    /* 0x60 */
    Instruction::LD_r8_r8(Register8::H, Register8::B),
    Instruction::LD_r8_r8(Register8::H, Register8::C),
    Instruction::LD_r8_r8(Register8::H, Register8::D),
    Instruction::LD_r8_r8(Register8::H, Register8::E),
    Instruction::LD_r8_r8(Register8::H, Register8::H),
    Instruction::LD_r8_r8(Register8::H, Register8::L),
    Instruction::LD_r8_HLINDIRECT(Register8::H),
    Instruction::LD_r8_r8(Register8::H, Register8::A),
    Instruction::LD_r8_r8(Register8::L, Register8::B),
    Instruction::LD_r8_r8(Register8::L, Register8::C),
    Instruction::LD_r8_r8(Register8::L, Register8::D),
    Instruction::LD_r8_r8(Register8::L, Register8::E),
    Instruction::LD_r8_r8(Register8::L, Register8::H),
    Instruction::LD_r8_r8(Register8::L, Register8::L),
    Instruction::LD_r8_HLINDIRECT(Register8::L),
    Instruction::LD_r8_r8(Register8::L, Register8::A),
    /* 0x70 */
    Instruction::LD_HLINDIRECT_r8(Register8::B),
    Instruction::LD_HLINDIRECT_r8(Register8::C),
    Instruction::LD_HLINDIRECT_r8(Register8::D),
    Instruction::LD_HLINDIRECT_r8(Register8::E),
    Instruction::LD_HLINDIRECT_r8(Register8::H),
    Instruction::LD_HLINDIRECT_r8(Register8::L),
    Instruction::HALT,
    Instruction::LD_HLINDIRECT_r8(Register8::A),
    Instruction::LD_r8_r8(Register8::A, Register8::B),
    Instruction::LD_r8_r8(Register8::A, Register8::C),
    Instruction::LD_r8_r8(Register8::A, Register8::D),
    Instruction::LD_r8_r8(Register8::A, Register8::E),
    Instruction::LD_r8_r8(Register8::A, Register8::H),
    Instruction::LD_r8_r8(Register8::A, Register8::L),
    Instruction::LD_r8_HLINDIRECT(Register8::A),
    Instruction::LD_r8_r8(Register8::A, Register8::A),
    /* 0x80 */
    Instruction::ADD_A_r8(Register8::B),
    Instruction::ADD_A_r8(Register8::C),
    Instruction::ADD_A_r8(Register8::D),
    Instruction::ADD_A_r8(Register8::E),
    Instruction::ADD_A_r8(Register8::H),
    Instruction::ADD_A_r8(Register8::L),
    Instruction::ADD_A_HL,
    Instruction::ADD_A_r8(Register8::A),
    Instruction::ADC_A_r8(Register8::B),
    Instruction::ADC_A_r8(Register8::C),
    Instruction::ADC_A_r8(Register8::D),
    Instruction::ADC_A_r8(Register8::E),
    Instruction::ADC_A_r8(Register8::H),
    Instruction::ADC_A_r8(Register8::L),
    Instruction::ADC_A_HL,
    Instruction::ADC_A_r8(Register8::A),
    /* 0x90 */
    Instruction::SUB_A_r8(Register8::B),
    Instruction::SUB_A_r8(Register8::C),
    Instruction::SUB_A_r8(Register8::D),
    Instruction::SUB_A_r8(Register8::E),
    Instruction::SUB_A_r8(Register8::H),
    Instruction::SUB_A_r8(Register8::L),
    Instruction::SUB_A_HL,
    Instruction::SUB_A_r8(Register8::A),
    Instruction::SBC_A_r8(Register8::B),
    Instruction::SBC_A_r8(Register8::C),
    Instruction::SBC_A_r8(Register8::D),
    Instruction::SBC_A_r8(Register8::E),
    Instruction::SBC_A_r8(Register8::H),
    Instruction::SBC_A_r8(Register8::L),
    Instruction::SBC_A_HL,
    Instruction::SBC_A_r8(Register8::A),
    /* 0xA0 */
    Instruction::AND_A_r8(Register8::B),
    Instruction::AND_A_r8(Register8::C),
    Instruction::AND_A_r8(Register8::D),
    Instruction::AND_A_r8(Register8::E),
    Instruction::AND_A_r8(Register8::H),
    Instruction::AND_A_r8(Register8::L),
    Instruction::AND_A_HL,
    Instruction::AND_A_r8(Register8::A),
    Instruction::XOR_A_r8(Register8::B),
    Instruction::XOR_A_r8(Register8::C),
    Instruction::XOR_A_r8(Register8::D),
    Instruction::XOR_A_r8(Register8::E),
    Instruction::XOR_A_r8(Register8::H),
    Instruction::XOR_A_r8(Register8::L),
    Instruction::XOR_A_HL,
    Instruction::XOR_A_r8(Register8::A),
    /* 0xB0 */
    Instruction::OR_A_r8(Register8::B),
    Instruction::OR_A_r8(Register8::C),
    Instruction::OR_A_r8(Register8::D),
    Instruction::OR_A_r8(Register8::E),
    Instruction::OR_A_r8(Register8::H),
    Instruction::OR_A_r8(Register8::L),
    Instruction::OR_A_HL,
    Instruction::OR_A_r8(Register8::A),
    Instruction::CP_A_r8(Register8::B),
    Instruction::CP_A_r8(Register8::C),
    Instruction::CP_A_r8(Register8::D),
    Instruction::CP_A_r8(Register8::E),
    Instruction::CP_A_r8(Register8::H),
    Instruction::CP_A_r8(Register8::L),
    Instruction::CP_A_HL,
    Instruction::CP_A_r8(Register8::A),
    /* 0xC0 */
    Instruction::RET_cc(Condition::NZ),
    Instruction::POP_r16(Register16::BC),
    Instruction::JP_cc_n16(Condition::NZ, 0),
    Instruction::JP_n16(0),
    Instruction::CALL_cc_n16(Condition::NZ, 0),
    Instruction::PUSH_r16(Register16::BC),
    Instruction::ADD_A_n8(0),
    Instruction::RST_vec(0x00),
    Instruction::RET_cc(Condition::Z),
    Instruction::RET,
    Instruction::JP_cc_n16(Condition::Z, 0),
    Instruction::ILLEGAL, // 0xCB - CB prefix
    Instruction::CALL_cc_n16(Condition::Z, 0),
    Instruction::CALL_n16(0),
    Instruction::ADC_A_n8(0),
    Instruction::RST_vec(0x08),
    /* 0xD0 */
    Instruction::RET_cc(Condition::NC),
    Instruction::POP_r16(Register16::DE),
    Instruction::JP_cc_n16(Condition::NC, 0),
    Instruction::ILLEGAL, // 0xD3
    Instruction::CALL_cc_n16(Condition::NC, 0),
    Instruction::PUSH_r16(Register16::DE),
    Instruction::SUB_A_n8(0),
    Instruction::RST_vec(0x10),
    Instruction::RET_cc(Condition::C),
    Instruction::RETI,
    Instruction::JP_cc_n16(Condition::C, 0),
    Instruction::ILLEGAL, // 0xDB
    Instruction::CALL_cc_n16(Condition::C, 0),
    Instruction::ILLEGAL, // 0xDD
    Instruction::SBC_A_n8(0),
    Instruction::RST_vec(0x18),
    /* 0xE0 */
    Instruction::LDH_n8_A(0),
    Instruction::POP_r16(Register16::HL),
    Instruction::LDH_C_A,
    Instruction::ILLEGAL, // 0xE3
    Instruction::ILLEGAL, // 0xE4
    Instruction::PUSH_r16(Register16::HL),
    Instruction::AND_A_n8(0),
    Instruction::RST_vec(0x20),
    Instruction::ADD_SP_e8(0),
    Instruction::JP_HL,
    Instruction::LD_n16_A(0),
    Instruction::ILLEGAL, // 0xEB
    Instruction::ILLEGAL, // 0xEC
    Instruction::ILLEGAL, // 0xED
    Instruction::XOR_A_n8(0),
    Instruction::RST_vec(0x28),
    /* 0xF0 */
    Instruction::LDH_A_n8(0),
    Instruction::POP_r16(Register16::AF),
    Instruction::LDH_A_C,
    Instruction::DI,
    Instruction::ILLEGAL, // 0xF4
    Instruction::PUSH_r16(Register16::AF),
    Instruction::OR_A_n8(0),
    Instruction::RST_vec(0x30),
    Instruction::LD_HL_SP_e8(0),
    Instruction::LD_SP_HL,
    Instruction::LD_A_n16(0),
    Instruction::EI,
    Instruction::ILLEGAL, // 0xFC
    Instruction::ILLEGAL, // 0xFD
    Instruction::CP_A_n8(0),
    Instruction::RST_vec(0x38),
];
